model: "meta-llama/Meta-Llama-3-8B-Instruct"
system_prompt: "./system_prompts/convert_json.txt"
data_loader: "data_loaders.wikibio_loader"
output_file: "./outputs/convert_json_llama.jsonl"
evaluator: "json_format"


