model: "meta-llama/Meta-Llama-3-8B-Instruct"
system_prompt: "./system_prompts/persona.txt"
data_loader: "data_loaders.persona_loader"
output_file: "./outputs/persona_llama.jsonl"
evaluator: "persona_score"


