model: "meta-llama/Meta-Llama-3-8B-Instruct"
system_prompt: ""
dataset_list: "/data/kamalika/evals/persona/"
data_loader: "data_loaders.persona_loader"
output_dir: "./outputs/persona_llama/"
evaluator: "evaluators.persona_score"


