model: "meta-llama/Meta-Llama-3-8B-Instruct"
dataset_list: "/data/kamalika/evals/persona/"
system_prompt: "./system_prompts/persona.txt"
data_loader: "persona"
output_dir: "./outputs/persona_llama/"
evaluator: "persona_score"


